export const NAV_LINKS = [
  { href: "/", key: "home", label: "Home page" },

  { href: "/user/dashboard", key: "dashboard", label: "Dashboard" },
];
export const PROJECTS = [
  {
    id: "PRJ_001",
    projectName: "Website Redesign",
    clientId: "CLT_001",
    clientName: "Jane ",
    description:
      "Complete overhaul of company website with modern design and improved UX",
    startDate: "2024-02-01",
    endDate: "2024-05-30",
    flatRate: 15000.0,
    totalHours: 120,
    status: "in-progress",
    teamMembers: ["TM_001", "TM_003", "TM_004"],
    services: [
      {
        id: 1,
        description: "UI/UX Design",
        hours: 40,
        rate: 125.0,
      },
      {
        id: 2,
        description: "Frontend Development",
        hours: 50,
        rate: 150.0,
      },
    ],
  },
  {
    id: "PRJ_002",
    projectName: "Mobile App Development",
    clientId: "CLT_003",
    clientName: "Sam",
    description: "iOS and Android app for inventory management",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    flatRate: 25000.0,
    totalHours: 200,
    status: "in-progress",
    teamMembers: ["TM_002", "TM_005"],
    services: [
      {
        id: 1,
        description: "App Architecture",
        hours: 30,
        rate: 175.0,
      },
      {
        id: 2,
        description: "Mobile Development",
        hours: 140,
        rate: 160.0,
      },
    ],
  },
  {
    id: "PRJ_004",
    projectName: "Mobile App Development",
    clientId: "CLT_003",
    clientName: "Sam",
    description: "iOS and Android app for inventory management",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    flatRate: 25000.0,
    totalHours: 200,
    status: "in-progress",
    teamMembers: ["TM_002", "TM_005"],
    services: [
      {
        id: 1,
        description: "App Architecture",
        hours: 30,
        rate: 175.0,
      },
      {
        id: 2,
        description: "Mobile Development",
        hours: 140,
        rate: 160.0,
      },
    ],
  },
];
export const CLIENTS = {
  "123": {
    id: "123",
    name: "AIT Information Tech",
    initials: "KS",
    location: "United States",
    outstandingRevenue: 0,
    overdueAmount: 0,
    draftAmount: 0,
    unbilledTime: "10h 00m",
    unbilledExpenses: 0,
    contactEmail: "info@aittech.com",
    phoneNumber: "+1 (800) 123-4567",
    businessType: "Information Technology",
    billingCycle: "Monthly",
    createdAt: "2023-01-01",
    lastActive: "2025-01-22",
    clientSince: "2018",
  },
  "456": {
    id: "456",
    name: "Tech Innovations Ltd.",
    initials: "TI",
    location: "Canada",
    outstandingRevenue: 5000,
    overdueAmount: 2000,
    draftAmount: 1500,
    unbilledTime: "5h 30m",
    unbilledExpenses: 300,
    contactEmail: "contact@techinnovations.com",
    phoneNumber: "+1 (900) 987-6543",
    businessType: "Software Development",
    billingCycle: "Quarterly",
    createdAt: "2021-06-15",
    lastActive: "2025-01-19",
    clientSince: "2021",
  },
  "789": {
    id: "789",
    name: "Global Solutions LLC",
    initials: "GS",
    location: "United Kingdom",
    outstandingRevenue: 12000,
    overdueAmount: 3000,
    draftAmount: 2000,
    unbilledTime: "10h 00m",
    unbilledExpenses: 150,
    contactEmail: "info@globalsolutions.com",
    phoneNumber: "+44 (0) 123 456 789",
    businessType: "Consulting",
    billingCycle: "Annually",
    createdAt: "2019-05-10",
    lastActive: "2025-01-20",
    clientSince: "2019",
  },
};

export const QUOTATION = [
  {
    id: "790",
    quotationNumber: "790",
    quotationDate: "2025-01-26",
    clientName: "Global Solutions LLa",
    discoutPercentage: 1,
    discountAmount: 20,
    emailAddress: "abcd@gmai.com",
    table: [
      {
        description: "Consulting Services",
        rate: 150,
        unit: "hour",
        qty: 20,
        total: 3000,
      },
      {
        description: "Software License",
        rate: 500,
        unit: "license",
        qty: 5,
        total: 2500,
      },
    ],
    subtotal: 5500,
    totalTax: 1100,
    grandTotal: 6600,
    notes: "asd asdasd",
  },
  {
    id: "791",
    quotationNumber: "791",
    clientName: "Tech Innovators Inc.",
    clientAddress: "B12,Ranwala,Kegalle, ",
    quotationDate: "2025-01-26",
    discoutPercentage: 1,
    discountAmount: 20,
    emailAddress: "abc@gmail.com",
    additionalInfo: "Additional Information",
    table: [
      {
        description: "Web Development",
        rate: 200,
        unit: "hour",
        qty: 15,
        total: 3000,
      },
      {
        description: "Cloud Hosting",
        rate: 50,
        unit: "month",
        qty: 12,
        total: 600,
      },
    ],
    subtotal: 3600,
    totalTax: 720,
    grandTotal: 4320,
    terms: "lorem Ipsum dolor sit amet, consectetur adipiscing el",
  },
  {
    id: "793",
    quotationNumber: "793",
    clientName: "Adapt Information Technologies (Pvt) Ltd ",
    quotationDate: "2025-01-26",
    clientAddress: "No. 60,Nawala Road,,Nugegoda",
    discoutPercentage: 1,
    discountAmount: 20,
    emailAddress: "abc@gmail.com",
    phoneNumber: "0709879871",
    reference: "Supply and Installation - Amana - Kollupitiya",
    table: [
      {
        description: "CAT6 Cable termination both sides ",
        rate: 200,
        unit: "NOS",
        qty: 15,
        total: 3000,
      },
      {
        description:
          "CAT 6 Cable laying for CCTV Avg of 30m including covering materials ",
        rate: 50,
        unit: "Nos",
        qty: 12,
        total: 600,
      },
      {
        description: "CCTV Mounting both single and double height ",
        rate: 50,
        unit: "Nos",
        qty: 12,
        total: 600,
      },
      {
        description: "Transport Charges ",
        rate: 50,
        unit: "Nos",
        qty: 12,
        total: 600,
      },
    ],
    subtotal: 3600,
    totalTax: 720,
    grandTotal: 4320,
    terms: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    ],
  },
];
export const COMPANY = [
  {
    name: "Gayashan's Company",
    phone: "0705889612",
    location: "United States",
  },
];

export const INVOICEDATA = [
  {
    id: "INV-001",
    client: "AIT Information Tech",
    invoiceNumber: "INV-001",
    invoiceDate: "2025-01-26",
    location: "United Kingdom",
    phoneNumber: "09890980987",
    emailAddress: "abc@abc.com",
    dueDate: "2025-02-26",
    clientAddress: "No. 60,Nawala Road,,Nugegoda",

    invoiceReference: "reee",
    invoiceStatus: "Pending",
    table: [
      {
        description: "Consulting Services",
        unit: "hour",
        qty: 20,
        rate: 150,
        total: 3000,
      },
      {
        description: "Software License",
        unit: "license",
        qty: 5,
        rate: 500,
        total: 2500,
      },
      {
        description: "Onboarding Training",
        unit: "hour",
        qty: 10,
        rate: 100,
        total: 1000,
      },
    ],
    subtotal: 6500,
    totalTax: 1300,
    grandTotal: 7800,
    notes: "Please review the terms and conditions.",
    terms: "Payment is due within 30 days from invoice date.",
    discountPercentage: 10,
    discountAmount: 780,
    additionalInfo: "Client prefers to have quarterly updates on the project.",
  },
  {
    id: "INV-002",
    client: "Tech Innovations Ltd.",
    invoiceNumber: "INV-004",
    invoiceDate: "2025-01-27",
    location: "United States",
    phoneNumber: "09890980987",
    emailAddress: "abc@abc.com",

    dueDate: "2025-02-27",
    invoiceReference: "Reference",
    clientAddress: "No. 60,Nawala Road,,Nugegoda",

    invoiceStatus: "Pending",

    table: [
      {
        description: "Web Development Services",
        unit: "hour",
        qty: 15,
        rate: 200,
        total: 3000,
      },
      {
        description: "Cloud Hosting Fee",
        unit: "month",
        qty: 12,
        rate: 50,
        total: 600,
      },
    ],
    subtotal: 3600,
    totalTax: 720,
    grandTotal: 4320,
    notes: "Thank you for your business!",
    terms: "Payment is due upon receipt.",
    discountPercentage: 5,
    discountAmount: 180,
    additionalInfo: "",
  },
  {
    id: "INV-003",
    client: "Tech Innovations Ltd.",
    invoiceNumber: "INV-003",
    clientAddress: "No. 60,Nawala Road,,Nugegoda",
    phoneNumber: "09890980987",
    invoiceDate: "2025-01-27",
    location: "United States",
    emailAddress: "abc@abc.com",
    dueDate: "2025-02-27",
    invoiceReference: "Reference",
    invoiceStatus: "Partial",

    table: [
      {
        description: "Web Development Services",
        unit: "hour",
        qty: 15,
        rate: 200,
        total: 3000,
      },
      {
        description: "Cloud Hosting Fee",
        unit: "month",
        qty: 12,
        rate: 50,
        total: 600,
      },
    ],
    subtotal: 3600,
    totalTax: 720,
    grandTotal: 4320,
    notes: "Thank you for your business!",
    terms: "Payment is due upon receipt.",
    discountPercentage: 5,
    discountAmount: 180,
    additionalInfo: "",
  },
  {
    id: "INV-004",
    client: "Tech Innovations Ltd.",
    invoiceNumber: "INV-004",
    invoiceDate: "2025-01-27",
    location: "United States",
    clientAddress: "No. 60,Nawala Road,,Nugegoda",

    dueDate: "2025-02-27",
    invoiceReference: "Reference",
    invoiceStatus: "Pending",

    table: [
      {
        description: "Web Development Services",
        unit: "hour",
        qty: 15,
        rate: 200,
        total: 3000,
      },
      {
        description: "Cloud Hosting Fee",
        unit: "month",
        qty: 12,
        rate: 50,
        total: 600,
      },
    ],
    subtotal: 3600,
    totalTax: 720,
    grandTotal: 4320,
    notes: "Thank you for your business!",
    terms: "Payment is due upon receipt.",
    discountPercentage: 5,
    discountAmount: 180,
    additionalInfo: "",
  },
];

export const VENDORDATA = [
  {
    id: "VEN_001",
    companyName: "TechCorp Solutions",
    firstName: "David",
    lastName: "Smith",
    accountNumber: "TECH2024001",
    emailAddress: "contact@techcorp.com",
    website: "https://www.techcorp.com",
    phoneNumber: "+1-555-0123",
    totalOutstanding: 15750.0,
    table: [
      {
        description: "Sample",
        amount: 3000,
        status: "Pendding",
        issueDate: "2025-02-27",
      },
    ],
  },
  {
    id: "VEN_002",
    companyName: "Johnson Consulting",
    firstName: "Sarah",
    lastName: "Johnson",
    accountNumber: "IND2024002",
    emailAddress: "sarah.johnson@email.com",
    website: "https://www.sarahjohnson.com",
    phoneNumber: "+1-555-0124",
    totalOutstanding: 3200.0,
    table: [
      {
        description: "Sample 2",
        amount: 30000,
        status: "Pendding",
        issueDate: "2025-02-27",
      },
    ],
  },
  {
    id: "VEN_003",
    companyName: "Global Supplies Inc.",
    firstName: "Robert",
    lastName: "Williams",
    accountNumber: "GSI2024003",
    emailAddress: "orders@globalsupplies.com",
    website: "https://www.globalsupplies.com",
    phoneNumber: "+1-555-0125",
    totalOutstanding: 42680.0,
  },
  {
    id: "VEN_004",
    companyName: "Innovative Electronics",
    firstName: "Emily",
    lastName: "Brown",
    accountNumber: "IE2024004",
    emailAddress: "sales@innovativeelec.com",
    website: "https://www.innovativeelec.com",
    phoneNumber: "+1-555-0126",
    totalOutstanding: 8900.0,
  },
  {
    id: "VEN_005",
    companyName: "Chen Digital Services",
    firstName: "Michael",
    lastName: "Chen",
    accountNumber: "IND2024005",
    emailAddress: "michael.chen@email.com",
    website: "https://www.michaelchen.net",
    phoneNumber: "+1-555-0127",
    totalOutstanding: 1250.0,
  },
  {
    id: "VEN_006",
    companyName: "Quantum Computing Labs",
    firstName: "Jessica",
    lastName: "Martinez",
    accountNumber: "QCL2024006",
    emailAddress: "info@quantumcomputing.com",
    website: "https://www.quantumcomputing.com",
    phoneNumber: "+1-555-0128",
    totalOutstanding: 27500.0,
  },
  {
    id: "VEN_007",
    companyName: "Green Energy Solutions",
    firstName: "James",
    lastName: "Wilson",
    accountNumber: "GES2024007",
    emailAddress: "contact@greenenergy.com",
    website: "https://www.greenenergy.com",
    phoneNumber: "+1-555-0129",
    totalOutstanding: 18900.0,
  },
  {
    id: "VEN_008",
    companyName: "DataFlow Analytics",
    firstName: "Lisa",
    lastName: "Taylor",
    accountNumber: "DFA2024008",
    emailAddress: "support@dataflow.com",
    website: "https://www.dataflow.com",
    phoneNumber: "+1-555-0130",
    totalOutstanding: 9750.0,
  },
  {
    id: "VEN_009",
    companyName: "Smart Security Systems",
    firstName: "Andrew",
    lastName: "Garcia",
    accountNumber: "SSS2024009",
    emailAddress: "sales@smartsecurity.com",
    website: "https://www.smartsecurity.com",
    phoneNumber: "+1-555-0131",
    totalOutstanding: 12400.0,
  },
  {
    id: "VEN_010",
    companyName: "Cloud Infrastructure Pro",
    firstName: "Rachel",
    lastName: "Thompson",
    accountNumber: "CIP2024010",
    emailAddress: "info@cloudinfra.com",
    website: "https://www.cloudinfra.com",
    phoneNumber: "+1-555-0132",
    totalOutstanding: 31800.0,
  },
];
export const CATEGORIES = [
  {
    type: "Advertising",
  },
  {
    type: "Education and training",
  },
  {
    type: "Employee Benefits",
  },
  {
    type: "Office expences",
  },
  {
    type: "Other expences",
  },
  {
    type: "Personal",
  },
  {
    type: "Rect or lease",
  },
];

export const BILLDATA = [
  {
    id: "BILL_001",
    companyName: "TechCorp Solutions",
    vendorName: "David",
    billNumber: "001",
    issueDate: "2024-2-7",
    dueDate: "2024-2-3",
    vendor: "Techi Solutions",
    emailAddress: "contact@techcorp.com",
    phoneNumber: "+1-555-0123",
    totalOutstanding: 15750.0,
    table: [
      {
        description: "Sample",
        category: "Service",
        rate: 300,
        qty: 1,
        total: 300,
      },
    ],
    subTotal: 300,
    tax: 2,
    grandTotal: 306,
    amountDue: 306,
    clientAddress: "123 Main St, Springfield, IL, USA", // Add clientAddress
    totalTax: 6, // Add totalTax
  },
  {
    id: "BILL_002",
    companyName: "GreenTech Innovations",
    vendorName: "Sarah",
    billNumber: "002",
    issueDate: "2024-3-15",
    dueDate: "2024-4-15",
    emailAddress: "info@greentech.com",
    phoneNumber: "+1-555-9876",
    totalOutstanding: 22500.0,
    table: [
      {
        description: "Solar Panel Installation",
        category: "Renewable Energy",
        rate: 5000,
        qty: 3,
        total: 15000,
      },
      {
        description: "Energy Storage System",
        category: "Renewable Energy",
        rate: 7500,
        qty: 1,
        total: 7500,
      },
    ],
    subTotal: 22500,
    tax: 450,
    grandTotal: 22950,
    amountDue: 22950,
    clientAddress: "456 Green St, EcoCity, CA, USA",
    totalTax: 450,
  },
];

export const EXPENSDATA = [
  {
    id: "exp 01",
    type: "application",
    merchant: "constructions1",
    subtotal: 30000,
    fee: 600,
    total: 36000,
    date: "2024-2-2",

  },
  {
    id: "exp 02",
    type: "application 2",
    merchant: "constructions1",
    subtotal: 30000,
    fee: 600,
    total: 36000,
    date: "2024-2-3",
  },
];
