export const NAV_LINKS = [
  { href: "/", key: "home", label: "Home page" },

  { href: "/user/dashboard", key: "dashboard", label: "Dashboard" },
];
export const PROJECTS = [
  {
    id: "PRJ_001",
    projectName: "Website Redesign",
    clientId: "CLT_001",
    clientName: "Jane ",
    description:
      "Complete overhaul of company website with modern design and improved UX",
    startDate: "2024-02-01",
    endDate: "2024-05-30",
    flatRate: 15000.0,
    totalHours: 120,
    status: "in-progress",
    teamMembers: ["TM_001", "TM_003", "TM_004"],
    services: [
      {
        id: 1,
        description: "UI/UX Design",
        hours: 40,
        rate: 125.0,
      },
      {
        id: 2,
        description: "Frontend Development",
        hours: 50,
        rate: 150.0,
      },
    ],
  },
  {
    id: "PRJ_002",
    projectName: "Mobile App Development",
    clientId: "CLT_003",
    clientName: "Sam",
    description: "iOS and Android app for inventory management",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    flatRate: 25000.0,
    totalHours: 200,
    status: "in-progress",
    teamMembers: ["TM_002", "TM_005"],
    services: [
      {
        id: 1,
        description: "App Architecture",
        hours: 30,
        rate: 175.0,
      },
      {
        id: 2,
        description: "Mobile Development",
        hours: 140,
        rate: 160.0,
      },
    ],
  },
];
export const CLIENTS = {
  "123": {
    id: "123",
    name: "AIT Information Tech",
    initials: "KS",
    location: "United States",
    outstandingRevenue: 0,
    overdueAmount: 0,
    draftAmount: 0,
    unbilledTime: "10h 00m",
    unbilledExpenses: 0,
    contactEmail: "info@aittech.com",
    phoneNumber: "+1 (800) 123-4567",
    businessType: "Information Technology",
    billingCycle: "Monthly",
    createdAt: "2023-01-01",
    lastActive: "2025-01-22",
    clientSince: "2018",
  },
  "456": {
    id: "456",
    name: "Tech Innovations Ltd.",
    initials: "TI",
    location: "Canada",
    outstandingRevenue: 5000,
    overdueAmount: 2000,
    draftAmount: 1500,
    unbilledTime: "5h 30m",
    unbilledExpenses: 300,
    contactEmail: "contact@techinnovations.com",
    phoneNumber: "+1 (900) 987-6543",
    businessType: "Software Development",
    billingCycle: "Quarterly",
    createdAt: "2021-06-15",
    lastActive: "2025-01-19",
    clientSince: "2021",
  },
  "789": {
    id: "789",
    name: "Global Solutions LLC",
    initials: "GS",
    location: "United Kingdom",
    outstandingRevenue: 12000,
    overdueAmount: 3000,
    draftAmount: 2000,
    unbilledTime: "10h 00m",
    unbilledExpenses: 150,
    contactEmail: "info@globalsolutions.com",
    phoneNumber: "+44 (0) 123 456 789",
    businessType: "Consulting",
    billingCycle: "Annually",
    createdAt: "2019-05-10",
    lastActive: "2025-01-20",
    clientSince: "2019",
  },
};

export const QUOTATION = [
  {
    id: "790",
    quotationNumber: "790",
    quotationDate: "2025-01-26",
    client: "Global Solutions LLa",
    discoutPercentage: 1,
    discountAmount: 20,
    table: [
      {
        description: "Consulting Services",
        rate: 150,
        unit: "hour",
        qty: 20,
        total: 3000,
      },
      {
        description: "Software License",
        rate: 500,
        unit: "license",
        qty: 5,
        total: 2500,
      },
    ],
    subtotal: 5500,
    totalTax: 1100,
    grandTotal: 6600,
    notes: "asd asdasd",
  },
  {
    id: "791",
    quotationNumber: "791",
    client: "Tech Innovators Inc.",
    quotationDate: "2025-01-26",

    discoutPercentage: 1,
    discountAmount: 20,
    table: [
      {
        description: "Web Development",
        rate: 200,
        unit: "hour",
        qty: 15,
        total: 3000,
      },
      {
        description: "Cloud Hosting",
        rate: 50,
        unit: "month",
        qty: 12,
        total: 600,
      },
    ],
    subtotal: 3600,
    totalTax: 720,
    grandTotal: 4320,
  },
];
export const COMPANY = [
  {
    name: "Gayashan's Company",
    phone: "0705889612",
    location: "United States",
  },
];

export const INVOICEDATA = [
  {
    id: "INV-001",
    client: "AIT Information Tech",
    invoiceNumber: "INV-001",
    invoiceDate: "2025-01-26",
    location: "United Kingdom",
    dueDate: "2025-02-26",
    invoiceReference: "reee",
    invoiceStatus: "Pending",
    table: [
      {
        description: "Consulting Services",
        unit: "hour",
        qty: 20,
        rate: 150,
        total: 3000,
      },
      {
        description: "Software License",
        unit: "license",
        qty: 5,
        rate: 500,
        total: 2500,
      },
      {
        description: "Onboarding Training",
        unit: "hour",
        qty: 10,
        rate: 100,
        total: 1000,
      },
    ],
    subtotal: 6500,
    totalTax: 1300,
    grandTotal: 7800,
    notes: "Please review the terms and conditions.",
    terms: "Payment is due within 30 days from invoice date.",
    discountPercentage: 10,
    discountAmount: 780,
    additionalInfo: "Client prefers to have quarterly updates on the project.",
  },
  {
    id: "INV-002",
    client: "Tech Innovations Ltd.",
    invoiceNumber: "INV-004",
    invoiceDate: "2025-01-27",
    location: "United States",
    dueDate: "2025-02-27",
    invoiceReference: "Reference",
    invoiceStatus: "Pending",

    table: [
      {
        description: "Web Development Services",
        unit: "hour",
        qty: 15,
        rate: 200,
        total: 3000,
      },
      {
        description: "Cloud Hosting Fee",
        unit: "month",
        qty: 12,
        rate: 50,
        total: 600,
      },
    ],
    subtotal: 3600,
    totalTax: 720,
    grandTotal: 4320,
    notes: "Thank you for your business!",
    terms: "Payment is due upon receipt.",
    discountPercentage: 5,
    discountAmount: 180,
    additionalInfo: "",
  },
  {
    id: "INV-003",
    client: "Tech Innovations Ltd.",
    invoiceNumber: "INV-003",
    invoiceDate: "2025-01-27",
    location: "United States",
    dueDate: "2025-02-27",
    invoiceReference: "Reference",
    invoiceStatus: "Partial",

    table: [
      {
        description: "Web Development Services",
        unit: "hour",
        qty: 15,
        rate: 200,
        total: 3000,
      },
      {
        description: "Cloud Hosting Fee",
        unit: "month",
        qty: 12,
        rate: 50,
        total: 600,
      },
    ],
    subtotal: 3600,
    totalTax: 720,
    grandTotal: 4320,
    notes: "Thank you for your business!",
    terms: "Payment is due upon receipt.",
    discountPercentage: 5,
    discountAmount: 180,
    additionalInfo: "",
  },
  {
    id: "INV-004",
    client: "Tech Innovations Ltd.",
    invoiceNumber: "INV-004",
    invoiceDate: "2025-01-27",
    location: "United States",
    dueDate: "2025-02-27",
    invoiceReference: "Reference",
    invoiceStatus: "Pending",

    table: [
      {
        description: "Web Development Services",
        unit: "hour",
        qty: 15,
        rate: 200,
        total: 3000,
      },
      {
        description: "Cloud Hosting Fee",
        unit: "month",
        qty: 12,
        rate: 50,
        total: 600,
      },
    ],
    subtotal: 3600,
    totalTax: 720,
    grandTotal: 4320,
    notes: "Thank you for your business!",
    terms: "Payment is due upon receipt.",
    discountPercentage: 5,
    discountAmount: 180,
    additionalInfo: "",
  },
];

export const VENDORDATA = [
  {
    id: "VEN_001",
    companyName: "TechCorp Solutions",
    firstName: "David",
    lastName: "Smith",
    accountNumber: "TECH2024001",
    emailAddress: "contact@techcorp.com",
    website: "https://www.techcorp.com",
    phoneNumber: "+1-555-0123",
    totalOutstanding: 15750.0,
    table: [
      {
        description: "Sample",
        amount: 3000,
        status: "Pendding",
        issueDate: "2025-02-27",
      },
    ],
  },
  {
    id: "VEN_002",
    companyName: "Johnson Consulting",
    firstName: "Sarah",
    lastName: "Johnson",
    accountNumber: "IND2024002",
    emailAddress: "sarah.johnson@email.com",
    website: "https://www.sarahjohnson.com",
    phoneNumber: "+1-555-0124",
    totalOutstanding: 3200.0,
    table: [
      {
        description: "Sample 2",
        amount: 30000,
        status: "Pendding",
        issueDate: "2025-02-27",
      },
    ],
  },
  {
    id: "VEN_003",
    companyName: "Global Supplies Inc.",
    firstName: "Robert",
    lastName: "Williams",
    accountNumber: "GSI2024003",
    emailAddress: "orders@globalsupplies.com",
    website: "https://www.globalsupplies.com",
    phoneNumber: "+1-555-0125",
    totalOutstanding: 42680.0,
  },
  {
    id: "VEN_004",
    companyName: "Innovative Electronics",
    firstName: "Emily",
    lastName: "Brown",
    accountNumber: "IE2024004",
    emailAddress: "sales@innovativeelec.com",
    website: "https://www.innovativeelec.com",
    phoneNumber: "+1-555-0126",
    totalOutstanding: 8900.0,
  },
  {
    id: "VEN_005",
    companyName: "Chen Digital Services",
    firstName: "Michael",
    lastName: "Chen",
    accountNumber: "IND2024005",
    emailAddress: "michael.chen@email.com",
    website: "https://www.michaelchen.net",
    phoneNumber: "+1-555-0127",
    totalOutstanding: 1250.0,
  },
  {
    id: "VEN_006",
    companyName: "Quantum Computing Labs",
    firstName: "Jessica",
    lastName: "Martinez",
    accountNumber: "QCL2024006",
    emailAddress: "info@quantumcomputing.com",
    website: "https://www.quantumcomputing.com",
    phoneNumber: "+1-555-0128",
    totalOutstanding: 27500.0,
  },
  {
    id: "VEN_007",
    companyName: "Green Energy Solutions",
    firstName: "James",
    lastName: "Wilson",
    accountNumber: "GES2024007",
    emailAddress: "contact@greenenergy.com",
    website: "https://www.greenenergy.com",
    phoneNumber: "+1-555-0129",
    totalOutstanding: 18900.0,
  },
  {
    id: "VEN_008",
    companyName: "DataFlow Analytics",
    firstName: "Lisa",
    lastName: "Taylor",
    accountNumber: "DFA2024008",
    emailAddress: "support@dataflow.com",
    website: "https://www.dataflow.com",
    phoneNumber: "+1-555-0130",
    totalOutstanding: 9750.0,
  },
  {
    id: "VEN_009",
    companyName: "Smart Security Systems",
    firstName: "Andrew",
    lastName: "Garcia",
    accountNumber: "SSS2024009",
    emailAddress: "sales@smartsecurity.com",
    website: "https://www.smartsecurity.com",
    phoneNumber: "+1-555-0131",
    totalOutstanding: 12400.0,
  },
  {
    id: "VEN_010",
    companyName: "Cloud Infrastructure Pro",
    firstName: "Rachel",
    lastName: "Thompson",
    accountNumber: "CIP2024010",
    emailAddress: "info@cloudinfra.com",
    website: "https://www.cloudinfra.com",
    phoneNumber: "+1-555-0132",
    totalOutstanding: 31800.0,
  },
];
